apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: example-namespace
spec:
  limits:
  - type: Container
    default:
      cpu: "0.5"
      memory: 500Mi
    defaultRequest:
      cpu: "0.5"
      memory: 500Mi
    #maxLimitRequestRatio:
      #cpu: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resource-quota
  namespace: example-namespace
spec:
  hard:
    #pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
