apiVersion: v1
kind: Pod
metadata:
  name: high-cpu-pod
spec:
  containers:
  - name: my-container
    image: my-image:latest
    resources:
      requests:
        cpu: "50"
        memory: "256Mi"
      limits:
        cpu: "100"
        memory: "512Mi"
